/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author intel
 */
public class pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form pembayaran
     */
    public pembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        brg2 = new javax.swing.JTextField();
        brg1 = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        brg3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        total = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Diskon");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 180, 100, 40);

        jLabel2.setText("Pembayaran");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 20, 110, 30);

        brg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg2ActionPerformed(evt);
            }
        });
        getContentPane().add(brg2);
        brg2.setBounds(150, 100, 110, 30);

        brg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg1ActionPerformed(evt);
            }
        });
        getContentPane().add(brg1);
        brg1.setBounds(150, 60, 110, 30);

        diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonActionPerformed(evt);
            }
        });
        getContentPane().add(diskon);
        diskon.setBounds(150, 180, 110, 30);

        brg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg3ActionPerformed(evt);
            }
        });
        getContentPane().add(brg3);
        brg3.setBounds(150, 140, 110, 30);

        jButton1.setText("BAYAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 220, 90, 30);

        total.setColumns(20);
        total.setRows(5);
        jScrollPane1.setViewportView(total);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 300, 170);

        jLabel6.setText("Harga Barang 1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 50, 100, 40);

        jLabel7.setText("Harga Barang 2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 90, 100, 40);

        jLabel8.setText("Harga Barang 3");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 140, 100, 40);

        setBounds(0, 0, 486, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void brg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg2ActionPerformed

    private void brg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg1ActionPerformed

    private void diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonActionPerformed

    private void brg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int Barang1 = Integer.parseInt(brg1.getText());
        int Barang2 = Integer.parseInt(brg2.getText());
        int Barang3 = Integer.parseInt(brg3.getText());
        int Disk = Integer.parseInt(diskon.getText());
        if (Disk==0)
            Disk=100;
        int Total, jumlah;
        
        Total = Barang1+Barang2+Barang3;
        jumlah = Barang1 * Disk / 100 + Barang2 * Disk / 100 + Barang3 * Disk / 100;
        
        total.setText("Harga Barang 1 : "+Barang1+
                "\nHarga Barang 2 : "+Barang2+
                "\nHarga Barang 3 : "+Barang3+
                "\nTotal Harga : "+ Total + 
                "\nJumlah Bayar : "+ jumlah + "\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea total;
    // End of variables declaration//GEN-END:variables
}
